#!/usr/bin/env python3

USER_HOME_DIR_ENT_IDX = 5

EXIT_CODE_BAD_KUBECONFIG = -100
EXIT_CODE_BAD_CONF_ARG = -200
EXIT_CODE_GET_SECRET_FAILED = -300
EXIT_CODE_PUT_SECRET_ENV_FILE_FAILED = -400
EXIT_CODE_PUT_SECRET_LITERAL_FAILED = -500
EXIT_CODE_DEL_SECRET_FAILED = -600
EXIT_CODE_GET_K8S_PROPS_FAILED = -700
EXIT_CODE_GET_PRIMARY_RESOURCES_FAILED = -800
EXIT_CODE_SET_PRIMARY_RESOURCES_FAILED = -900

OPTION_SPARK_DRIVER_DEFAULT_JAVA_OPTIONS = "spark.driver.defaultJavaOptions"
OPTION_SPARK_DRIVER_EXTRA_JAVA_OPTIONS = "spark.driver.extraJavaOptions"
OPTION_SPARK_EXECUTOR_DEFAULT_JAVA_OPTIONS = "spark.executor.defaultJavaOptions"
OPTION_SPARK_EXECUTOR_EXTRA_JAVA_OPTIONS = "spark.executor.extraJavaOptions"
