name: spark-client
base: core22
version: "3.5.1"
summary: Client side scripts to submit Spark jobs to a cluster.
description: |
  The spark-client snap includes the scripts spark-submit, spark-shell, pyspark and other tools for managing Apache Spark jobs.

grade: stable
confinement: strict

hooks:
  install:
    plugs:
      - home

plugs:
  dot-kube-config:
    interface: personal-files
    read:
      - $HOME/.kube/config

environment:
  JAVA_HOME: $SNAP/usr/lib/jvm/java-17-openjdk-amd64
  PATH: $JAVA_HOME/bin:$PATH:$SNAP:$SNAP/opt/$CRAFT_PROJECT_NAME:$SNAP/opt/k8s:$SNAP/opt/spark
  SPARK_HOME: $SNAP/opt/spark
  SPARK_CONFS: $SNAP_DATA/etc/spark8t/
  SPARK_USER_DATA: $HOME

apps:
  service-account-registry:
    command: etc/spark8t/launcher.sh $SNAP/lib/python3.10/site-packages/spark8t/cli/service_account_registry.py
    environment:
      PYTHONPATH: $SNAP/python:$SNAP/lib/python3.10/site-packages:$SNAP/local/lib/dist-packages/:$SNAP/local/lib/dist-packages/spark8t/cli:$PYTHONPATH
    plugs:
      - network
      - home
      - dot-kube-config
  spark-submit:
    command: etc/spark8t/launcher.sh $SNAP/lib/python3.10/site-packages/spark8t/cli/spark_submit.py
    environment:
      PYTHONPATH: $SNAP/python:$SNAP/lib/python3.10/site-packages:$PYTHONPATH
      _JAVA_OPTIONS: "-Duser.home=$SNAP_USER_DATA -Djavax.net.ssl.trustStore=$SNAP_DATA/etc/ssl/certs/java/cacerts -Djavax.net.ssl.trustStorePassword=changeit"
    plugs:
      - network
      - home
      - dot-kube-config
  spark-shell:
    command: etc/spark8t/launcher.sh $SNAP/lib/python3.10/site-packages/spark8t/cli/spark_shell.py $SPARK8T_EXTRA_CONF
    environment:
      PYTHONPATH: $SNAP/python:$SNAP/lib/python3.10/site-packages:$PYTHONPATH
      SPARK8T_EXTRA_CONF: --conf spark.driver.extraJavaOptions="-Duser.home=$SNAP_USER_DATA" --conf spark.jars.ivy=/tmp
      _JAVA_OPTIONS: "-Duser.home=$SNAP_USER_DATA -Djavax.net.ssl.trustStore=$SNAP_DATA/etc/ssl/certs/java/cacerts -Djavax.net.ssl.trustStorePassword=changeit"
    plugs:
      - network
      - network-bind
      - home
      - dot-kube-config
  pyspark:
    command: etc/spark8t/launcher.sh $SNAP/lib/python3.10/site-packages/spark8t/cli/pyspark.py $SPARK8T_EXTRA_CONF
    environment:
      PYTHONPATH: $SNAP/python:$SNAP/lib/python3.10/site-packages:$PYTHONPATH
      SPARK8T_EXTRA_CONF: --conf spark.driver.extraJavaOptions="-Duser.home=$SNAP_USER_DATA" --conf spark.jars.ivy=/tmp
      _JAVA_OPTIONS: "-Duser.home=$SNAP_USER_DATA -Djavax.net.ssl.trustStore=$SNAP_DATA/etc/ssl/certs/java/cacerts -Djavax.net.ssl.trustStorePassword=changeit"
    plugs:
      - network
      - network-bind
      - home
      - dot-kube-config
  spark-sql:
    command: etc/spark8t/launcher.sh $SNAP/lib/python3.10/site-packages/spark8t/cli/spark_sql.py $SPARK8T_EXTRA_CONF
    environment:
      PYTHONPATH: $SNAP/python:$SNAP/lib/python3.10/site-packages:$PYTHONPATH
      SPARK8T_EXTRA_CONF: --conf spark.driver.extraJavaOptions="-Duser.home=$SNAP_USER_DATA" --conf spark.jars.ivy=/tmp
      _JAVA_OPTIONS: "-Duser.home=$SNAP_USER_DATA -Djavax.net.ssl.trustStore=$SNAP_DATA/etc/ssl/certs/java/cacerts -Djavax.net.ssl.trustStorePassword=changeit"
    plugs:
      - network
      - network-bind
      - home
      - dot-kube-config

  import-certificate:
    command: etc/spark8t/bin/import-certificate.sh
    environment:
      _JAVA_OPTIONS: "-Duser.home=$SNAP_USER_DATA"
    plugs:
      - network
      - network-bind
      - home
      - dot-kube-config

  beeline:
    command: /opt/kyuubi/bin/kyuubi-beeline
    environment:
      _JAVA_OPTIONS: "-Duser.home=$SNAP_USER_DATA"
    plugs:
      - network
      - network-bind

parts:
  spark8t-conf:
    plugin: dump
    source: snap/local
    override-prime: |
      craftctl default
      chmod +x etc/spark8t/bin/import-certificate.sh
      mkdir -p home/ubuntu
      chmod u+x home/ubuntu/

  spark8t:
    plugin: python
    python-packages:
      - https://github.com/canonical/spark-k8s-toolkit-py/releases/download/v0.0.10/spark8t-0.0.10-py3-none-any.whl
    source: .
    build-packages:
      - python3
      - pip
    override-build: |
      craftctl default
      # Scripts must be executable
      chmod -R 755 $CRAFT_PART_INSTALL/lib/python3.10/site-packages/spark8t/cli/

  spark:
    plugin: nil
    build-packages:
      - ca-certificates
      - ca-certificates-java
      - openjdk-17-jre-headless
      - wget
    stage-packages:
      - openjdk-17-jre-headless
    override-build: |
      SPARK_VERSION=$(cat $CRAFT_PROJECT_DIR/SPARK_VERSION | tr -d '\n')
      TAG=$( echo ${SPARK_VERSION%-*} )
      TARBALL_URL="https://github.com/canonical/central-uploader/releases/download/spark-${TAG}/spark-${SPARK_VERSION}-bin-k8s.tgz"
      CHECKSUM_URL="${TARBALL_URL}.sha512"

      STATUSCODE=$(curl --silent --head $TARBALL_URL | head -n 1 | cut -d' ' -f2)

      if  [[ ${STATUSCODE} -gt 400 ]]
        then
          echo "ERROR: Latest available Spark version spark-${SPARK_VERSION} does not have a downloadable binary! Exiting...."
          exit 1
      fi
      echo "Downloading latest available Spark version spark-${SPARK_VERSION}."
      wget $TARBALL_URL
      wget $CHECKSUM_URL
      sha512sum --check "spark-${SPARK_VERSION}-bin-k8s.tgz.sha512"
      if  [[ $? -ne 0 ]]
        then
          echo "DOWNLOAD ERROR: Latest available Spark version spark-${SPARK_VERSION} could not be downloaded properly! Exiting...."
          exit 1
      fi
      tar -zxf "spark-${SPARK_VERSION}-bin-k8s.tgz"
      cd "spark-${SPARK_VERSION}-bin-k8s/"
      SPARK_DIR=$CRAFT_PART_INSTALL/opt/spark
      mkdir -p $SPARK_DIR/bin
      cp -r bin/* $SPARK_DIR/bin
      mkdir -p $SPARK_DIR/jars
      cp -r jars/* $SPARK_DIR/jars
      mkdir -p $SPARK_DIR/python
      cp -r python/* $SPARK_DIR/python/

    override-prime: |
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-17-openjdk-*/lib/security/blacklisted.certs
      # move base certs data
      mv etc/ssl/certs/java/cacerts etc/cacerts

  kyuubi-beeline:
    plugin: nil
    build-packages:
      - wget
    override-build: |
      KYUUBI_ARTIFACT="https://dlcdn.apache.org/kyuubi/kyuubi-1.10.1/apache-kyuubi-1.10.1-bin.tgz"
      KYUUBI_512_CHECKSUM="9b565bb7c628a50ecd394741eedb9a5154590709603e26f81de88ffd3b5256603215e71160de61360b8f2e2842116026c2f9ed3a60a8f0356388e3dd2c00b84c"
      KYUUBI_TARFILE="kyuubi.tar.tgz"

      # Download and verify Kyuubi
      wget -O $KYUUBI_TARFILE $KYUUBI_ARTIFACT
      echo "$KYUUBI_512_CHECKSUM  $KYUUBI_TARFILE" | sha512sum -c -

      # Create the target directories and extract the tarball for Kyuubi
      KYUUBI_DIR=$CRAFT_PART_INSTALL/opt/kyuubi
      mkdir -p $KYUUBI_DIR/bin
      mkdir -p $KYUUBI_DIR/logs
      mkdir -p $KYUUBI_DIR/work
      mkdir -p $KYUUBI_DIR/pid
      mkdir -p $KYUUBI_DIR/externals/kyuubi-download/target
      mkdir kyuubi
      tar -xzvf $KYUUBI_TARFILE -C kyuubi/ --strip-components=1

      # Resolve beeline jars symlinks, save ~50MB compared to copying kyuubi jars folder
      for f in $(find kyuubi/beeline-jars -maxdepth 1 -type l)
      do
          cp --remove-destination $(readlink -e $f) $f
      done

      # Stage beeline files
      cp -r kyuubi/beeline-jars $KYUUBI_DIR
      cp kyuubi/bin/kyuubi-beeline $KYUUBI_DIR/bin
      cp kyuubi/bin/load-kyuubi-env.sh $KYUUBI_DIR/bin
      chmod -R +x $KYUUBI_DIR/bin

  kubectl:
    plugin: nil
    build-packages:
      - curl
    source: .
    source-type: local
    override-build: |
      craftctl default
      curl -LO -s "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      chmod +x kubectl
      K8S_DIR=$CRAFT_PART_INSTALL/opt/k8s
      mkdir -p $K8S_DIR
      cp kubectl $K8S_DIR
