name: spark-client
base: core22
version: "4.0.2"
summary: Client side scripts to submit Spark jobs to a cluster.
description: |
  The spark-client snap includes the scripts spark-submit, spark-shell, pyspark and other tools for managing Apache Spark jobs.
source-code: https://github.com/canonical/spark-client-snap
issues: https://github.com/canonical/spark-client-snap/issues/new/choose
website:
  - https://ubuntu.com/data/spark
  - https://canonical.com/data/docs/spark/k8s
contact: https://matrix.to/#/%23charmhub-analytics%3Aubuntu.com
license: Apache-2.0

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [arm64]
    build-for: [arm64]
grade: stable
confinement: strict

hooks:
  install:
    plugs:
      - home

plugs:
  dot-kube-config:
    interface: personal-files
    read:
      - $HOME/.kube/config

environment:
  JAVA_HOME: $SNAP/usr/lib/jvm/java-17-openjdk-${CRAFT_ARCH_BUILD_FOR}
  PATH: $JAVA_HOME/bin:$SNAP/bin:$SNAP/opt/$CRAFT_PROJECT_NAME:$SNAP/opt/k8s:$SNAP/opt/spark:$PATH
  SPARK_HOME: $SNAP/opt/spark
  SPARK_CONFS: $SNAP_DATA/etc/spark8t/
  SPARK_USER_DATA: $HOME
  AWS_JAVA_V1_DISABLE_DEPRECATION_ANNOUNCEMENT: "true"

apps:
  service-account-registry:
    command: etc/spark8t/launcher.sh $SNAP/bin/service-account-registry
    plugs:
      - network
      - home
      - dot-kube-config
  spark-submit:
    command: etc/spark8t/launcher.sh $SNAP/bin/spark-submit
    environment:
      _JAVA_OPTIONS: "-Duser.home=$SNAP_USER_DATA -Djavax.net.ssl.trustStore=$SNAP_DATA/etc/ssl/certs/java/cacerts -Djavax.net.ssl.trustStorePassword=changeit"
    plugs:
      - network
      - home
      - dot-kube-config
  spark-shell:
    command: etc/spark8t/launcher.sh $SNAP/bin/spark-shell $SPARK8T_EXTRA_CONF
    environment:
      SPARK8T_EXTRA_CONF: |
        --conf spark.driver.extraJavaOptions="-Duser.home=$SNAP_USER_DATA" \
        --conf spark.jars.ivy=/tmp \
        --conf spark.metrics.conf.driver.sink.prometheus.class=org.apache.spark.metrics.sink.JmxSink
      _JAVA_OPTIONS: "-Duser.home=$SNAP_USER_DATA -Djavax.net.ssl.trustStore=$SNAP_DATA/etc/ssl/certs/java/cacerts -Djavax.net.ssl.trustStorePassword=changeit"
    plugs:
      - network
      - network-bind
      - home
      - dot-kube-config
  pyspark:
    command: etc/spark8t/launcher.sh $SNAP/bin/pyspark $SPARK8T_EXTRA_CONF
    environment:
      SPARK8T_EXTRA_CONF: |
        --conf spark.driver.extraJavaOptions="-Duser.home=$SNAP_USER_DATA" \
        --conf spark.jars.ivy=/tmp \
        --conf spark.metrics.conf.driver.sink.prometheus.class=org.apache.spark.metrics.sink.JmxSink
      _JAVA_OPTIONS: "-Duser.home=$SNAP_USER_DATA -Djavax.net.ssl.trustStore=$SNAP_DATA/etc/ssl/certs/java/cacerts -Djavax.net.ssl.trustStorePassword=changeit"
    plugs:
      - network
      - network-bind
      - home
      - dot-kube-config
  spark-sql:
    command: etc/spark8t/launcher.sh $SNAP/bin/spark-sql $SPARK8T_EXTRA_CONF
    environment:
      SPARK8T_EXTRA_CONF: |
        --conf spark.driver.extraJavaOptions="-Duser.home=$SNAP_USER_DATA" \
        --conf spark.jars.ivy=/tmp \
        --conf spark.metrics.conf.driver.sink.prometheus.class=org.apache.spark.metrics.sink.JmxSink
      _JAVA_OPTIONS: "-Duser.home=$SNAP_USER_DATA -Djavax.net.ssl.trustStore=$SNAP_DATA/etc/ssl/certs/java/cacerts -Djavax.net.ssl.trustStorePassword=changeit"
    plugs:
      - network
      - network-bind
      - home
      - dot-kube-config

  import-certificate:
    command: etc/spark8t/bin/import-certificate.sh
    environment:
      _JAVA_OPTIONS: "-Duser.home=$SNAP_USER_DATA"
    plugs:
      - home

  beeline:
    command: opt/spark/bin/beeline
    environment:
      _JAVA_OPTIONS: "-Duser.home=$SNAP_USER_DATA"
    plugs:
      - network
      - network-bind

parts:
  spark8t-conf:
    plugin: dump
    source: snap/local
    override-prime: |
      craftctl default
      chmod +x etc/spark8t/bin/import-certificate.sh
      mkdir -p home/ubuntu
      chmod u+x home/ubuntu/

  spark8t:
    plugin: python
    python-packages:
      # renovate: datasource=pypi
      - spark8t==1.4.0
    source: ""

  spark:
    plugin: dump
    # renovate: datasource=github-releases depName=canonical/central-uploader depType=spark-source
    source: https://github.com/Batalex/charmed-spark-rock/releases/download/4.0.2-netty-4.2/spark-4.0.2-ubuntu1-20260608125354-bin-k8s.tgz
    organize:
      jars: opt/spark/jars
      bin: opt/spark/bin
      python: opt/spark/python
    build-packages:
      - ca-certificates
      - ca-certificates-java
    stage-packages:
      - openjdk-17-jre-headless
    stage:
      - etc/
      - opt/spark/bin
      - -opt/spark/bin/beeline
      - opt/spark/jars
      - opt/spark/python
      - usr/
    override-prime: |
      craftctl default
      rm -vf usr/lib/jvm/java-17-openjdk-${CRAFT_ARCH_BUILD_FOR}/lib/security/blacklisted.certs
      # move base certs data
      mv etc/ssl/certs/java/cacerts etc/cacerts

  kubectl:
    plugin: nil
    build-packages:
      - curl
    source: .
    source-type: local
    override-build: |
      craftctl default
      curl -LO -s "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/$CRAFT_ARCH_BUILD_FOR/kubectl"
      chmod +x kubectl
      K8S_DIR=$CRAFT_PART_INSTALL/opt/k8s
      mkdir -p $K8S_DIR
      cp kubectl $K8S_DIR
