name: Build snap and run tests

on:
  workflow_call:
    outputs:
      snap-file:
        description: "The snap output of build process."
        value: ${{ jobs.build.outputs.snap-file }}

jobs:
  lint:
    name: Lint
    uses: canonical/data-platform-workflows/.github/workflows/lint.yaml@v32.0.0

  build:
    name: Build snap
    uses: canonical/data-platform-workflows/.github/workflows/build_snap.yaml@v32.0.0

  test:
    name: Test Snap
    runs-on: ubuntu-22.04
    timeout-minutes: 90
    needs:
      - lint
      - build
    steps:
      - name: Download snap file
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact-prefix }}
          path: .

      - name: Install snap file
        run: |
          sudo snap install ${{ needs.build.outputs.artifact-prefix }} --dangerous

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup microceph
        id: microceph
        uses: canonical/microceph-action@v0.2
        with:
          channel: 'latest/stable'
          accesskey: 'accesskey'
          secretkey: 'secretkey'
          bucket: 'testbucket'
          osdsize: '3G'

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup MicroK8s
        run: |
          make microk8s

      - name: Run Integration Tests
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: |
          sg microk8s -c "make integration-tests"
