name: Release to channels

on:
  push:
    branches:
      - 3.4/*
      - 3.5/*
      - 4.0/*

permissions:
  contents: read

jobs:
  release_checks:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Extract branch metadata
        shell: bash
        run: |
          BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "branch=${BRANCH}" >> $GITHUB_OUTPUT
          echo "track=${BRANCH%*\/*}" >> $GITHUB_OUTPUT
        id: branch_metadata
      - name: Check consistency between metadata and release branch
        run: |
          RAW_VERSION=$(yq '(.version|split("-"))[0]' snap/snapcraft.yaml)
          MAJOR_MINOR_VERSION=$(echo $RAW_VERSION | sed -n "s/\(^[0-9]*\.[0-9]*\).*/\1/p")
          if [ "${MAJOR_MINOR_VERSION}" != "${{ steps.branch_metadata.outputs.track }}" ]; then exit 1; fi
        continue-on-error: false

      - name: Output Branch Metadata information
        run: |
          echo "Branch: ${{ steps.branch_metadata.outputs.branch }}"
          echo "Track: ${{ steps.branch_metadata.outputs.track }}"

    outputs:
      branch: ${{ steps.branch_metadata.outputs.branch }}
      track: ${{ steps.branch_metadata.outputs.track }}

  build:
    name: Build snap
    uses: canonical/data-platform-workflows/.github/workflows/build_snap.yaml@v48.0.2
    permissions:
      actions: read
      contents: read

  release:
    name: Release snap
    needs:
      - build
      - release_checks
    uses: canonical/data-platform-workflows/.github/workflows/release_snap_edge.yaml@v48.0.2
    with:
      track: ${{ needs.release_checks.outputs.track }}
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
    secrets:
      snap-store-token: ${{ secrets.SNAP_STORE_TOKEN }}
    permissions:
      actions: read
      contents: write # Needed to create GitHub release
