#!/usr/bin/env bash

set -eux

export COMPONENT=${SNAP_NAME}

export LOGS="${SNAP_COMMON}"/var/log/$COMPONENT
export DATA="${SNAP_COMMON}"/var/lib/$COMPONENT

mkdir -p $LOGS
mkdir -p $DATA

cp -r $SNAP/etc/ ${SNAP_DATA}

chmod -R 775 "${SNAP_DATA}"/*
chmod -R 775 "${SNAP_COMMON}"/*
